<a href="https://colab.research.google.com/github/KuroCat-bite/Practice/blob/main/Indexing_%26_Mathematics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexing

In [39]:
import numpy as np

In [ ]:
data = np.arange(100, 200)
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [ ]:
data[0]

100

In [ ]:
fives = np.arange(0, 100, 5)
fives

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
data[fives]

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [ ]:
data2D = data.reshape(10, -1)
data2D

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [ ]:
print(data.ndim)

1


In [ ]:
data2D[2]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [ ]:
data2D[2, :]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [ ]:
data2D[:, 3]

array([103, 113, 123, 133, 143, 153, 163, 173, 183, 193])

In [ ]:
data2D[2, 1]

121

In [ ]:
data2D[-1, -1]

199

In [ ]:
data2D[1:4, 3:5]

array([[113, 114],
       [123, 124],
       [133, 134]])

# Mathematics

In [ ]:
numbers = np.random.random((5, 5))
numbers

array([[0.22673715, 0.73077144, 0.12577922, 0.22493438, 0.61265633],
       [0.38005856, 0.82056677, 0.90772837, 0.39881845, 0.9440801 ],
       [0.99588478, 0.36462241, 0.66181215, 0.71250736, 0.71203616],
       [0.50273299, 0.06322567, 0.7185342 , 0.99605358, 0.51358626],
       [0.41753501, 0.01085191, 0.08920747, 0.98650545, 0.63222238]])

In [ ]:
print(np.amin(numbers))
print(np.amax(numbers))
print(np.average(numbers))
print(np.sum(numbers))

0.010851905192413192
0.9960535793946121
0.5499779415771482
13.749448539428705


In [ ]:
np.sqrt(numbers)

array([[0.47616925, 0.85485171, 0.35465366, 0.47427247, 0.78272366],
       [0.6164889 , 0.9058514 , 0.9527478 , 0.63152074, 0.97163784],
       [0.99794027, 0.60383972, 0.81351838, 0.84410151, 0.84382235],
       [0.70903666, 0.25144715, 0.84766397, 0.99802484, 0.71664933],
       [0.64616949, 0.10417248, 0.29867619, 0.99322981, 0.79512413]])

In [ ]:
np.sin(numbers)

array([[0.22479939, 0.66744429, 0.12544784, 0.2230424 , 0.57504269],
       [0.37097485, 0.73153237, 0.7881075 , 0.38832979, 0.80995777],
       [0.8392404 , 0.35659655, 0.61454743, 0.6537332 , 0.65337657],
       [0.48182217, 0.06318355, 0.65828197, 0.83933218, 0.49130399],
       [0.40550846, 0.01085169, 0.0890892 , 0.83410345, 0.59093905]])

In [ ]:
sample = np.arange(1, 21)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
sample + sample

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [ ]:
sample2 = np.arange(51, 71)
sample2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

In [ ]:
sample + sample2

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90])

In [ ]:
sample -sample2

array([-50, -50, -50, -50, -50, -50, -50, -50, -50, -50, -50, -50, -50,
       -50, -50, -50, -50, -50, -50, -50])

In [ ]:
sample2-sample

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])

In [ ]:
sample2//sample

array([51, 26, 17, 13, 11,  9,  8,  7,  6,  6,  5,  5,  4,  4,  4,  4,  3,
        3,  3,  3])

In [ ]:
tup1 = ('fisika', 'kimia', 1993, 2017)
tup2 = np.arange(1, 8)
print(tup1)
print(tup2)

('fisika', 'kimia', 1993, 2017)
[1 2 3 4 5 6 7]


# Matrix

In [ ]:
matrix = np.random.randint(1, 50,20)
matrix

array([22, 35, 47, 24, 47, 16,  3, 48, 42, 34, 22, 18, 36, 24, 39, 30,  4,
       47, 10, 41])

In [ ]:
matrix = matrix.reshape(4, -1)
matrix

array([[22, 35, 47, 24, 47],
       [16,  3, 48, 42, 34],
       [22, 18, 36, 24, 39],
       [30,  4, 47, 10, 41]])

In [ ]:
matrix = matrix.reshape(4, -1)
matrix

array([[23, 34, 10, 41, 30],
       [37, 26, 30, 46, 38],
       [18, 34, 32, 46, 39],
       [47, 35, 32, 48, 17]])

In [ ]:
matrix.transpose()

array([[23, 37, 18, 47],
       [34, 26, 34, 35],
       [10, 30, 32, 32],
       [41, 46, 46, 48],
       [30, 38, 39, 17]])

In [ ]:
np.dot(matrix, -1)

array([[-23, -34, -10, -41, -30],
       [-37, -26, -30, -46, -38],
       [-18, -34, -32, -46, -39],
       [-47, -35, -32, -48, -17]])

In [54]:
a1 = np.arange(16)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
b1 = np.arange(16)
b1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
np.dot(a1, b1)

935

In [56]:
a1 = a1.reshape(4, 4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
b1 = b1.reshape(4, 4)
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
a1@b1

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [59]:
np.matmul(a1, b1)

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])