<a href="https://colab.research.google.com/github/KuroCat-bite/Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [2]:
import numpy as np

Array dengan rank 1 panjang 3

In [4]:
([1, 2, 3])

[1, 2, 3]

Array dengan rank 2 panjang 3

In [5]:
([1, 2, 3] , [4, 5, 6])

([1, 2, 3], [4, 5, 6])

In [8]:
a= np.array([1, 2, 3])
b= np.array([(1, 2, 3), (4, 5, 6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
