<a href="https://colab.research.google.com/github/KuroCat-bite/Practice/blob/main/Properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Properties
* ndarray.ndim : dimensi (rank) dari sebuah nump array
* ndarray.shape : baris dan kolum dari sebuah numpy array
* ndarray.size : jumlah elemen di numpy array
* ndarray.dtype : tipe data dari elemen yang ada di numpy array
* ndarray.itemsize : ukuran elemen (bytes) yang ada di numpy array
* ndarray.data : buffer untuk menyimpan elemen-elemen di numpy array


In [3]:
import numpy as np

In [4]:
a= np.array([1, 2, 3])
b= np.array([(1, 2, 3), (4, 5, 6)])

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [6]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


Create Numpy Arrays

* np.zeros : isinya semua 0
* np.ones : isinya semua 1
* np.arange : berikan scop (start, stop, step) dan panjang dari step
* np.linspace : berikan scope dan jumlah elemen yang diinginkan
* np.random.random : memberikan angka acak


In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.arange(1, 2, 0.2)


array([1. , 1.2, 1.4, 1.6, 1.8])

In [27]:
np.linspace(1, 3, 10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [28]:
np.random.random((2, 3))

array([[0.62050198, 0.27732336, 0.07009265],
       [0.90568594, 0.20751458, 0.51972922]])