<a href="https://colab.research.google.com/github/KuroCat-bite/Practice/blob/main/Shape_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shape and Operation

* reshape : mengubah dimensi (shape) dari sebuah numpy array
* vstack : stack numpy arrays secara vertikal
* hstack : stack numpy arrays secara horizontal
* vsplit : split numpy arrays secara vertikal
* hsplit : split numpy arrays secara horizontal

In [2]:
import numpy as np

In [85]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a = a.reshape((3, -1))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
b = np.array([(7, 8), (9, 10,)])

B

array([[ 7,  8,  9],
       [ 9, 10, 11]])

In [83]:
np.vstack ((a, b))


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [71]:
c = np.array([(11, 12, 13), (14, 15, 16)])

c

array([[11, 12, 13],
       [14, 15, 16]])

In [87]:
d = np.array((a, c))

d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [89]:
d = np.hstack((a, c))

d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [91]:
np.vsplit(d, 2)

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [100]:
np.hsplit(d, 3) 

[array([[1, 2],
        [4, 5]]), array([[ 3, 11],
        [ 6, 14]]), array([[12, 13],
        [15, 16]])]

In [96]:
 np.hsplit(d, (1, 3)) # split setelah kolum 1 dan kolum 3

[array([[1],
        [4]]), array([[2, 3],
        [5, 6]]), array([[11, 12, 13],
        [14, 15, 16]])]

In [3]:
e = np.array(((1, 2, 3,), (4, 5, 6), (7, 8, 9)))
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
f = np.array((10, 11, 12))
f

array([10, 11, 12])

In [15]:
np.linspace(f,(10, 12, 0.5 ))


array([[10.        , 11.        , 12.        ],
       [10.        , 11.02040816, 11.76530612],
       [10.        , 11.04081633, 11.53061224],
       [10.        , 11.06122449, 11.29591837],
       [10.        , 11.08163265, 11.06122449],
       [10.        , 11.10204082, 10.82653061],
       [10.        , 11.12244898, 10.59183673],
       [10.        , 11.14285714, 10.35714286],
       [10.        , 11.16326531, 10.12244898],
       [10.        , 11.18367347,  9.8877551 ],
       [10.        , 11.20408163,  9.65306122],
       [10.        , 11.2244898 ,  9.41836735],
       [10.        , 11.24489796,  9.18367347],
       [10.        , 11.26530612,  8.94897959],
       [10.        , 11.28571429,  8.71428571],
       [10.        , 11.30612245,  8.47959184],
       [10.        , 11.32653061,  8.24489796],
       [10.        , 11.34693878,  8.01020408],
       [10.        , 11.36734694,  7.7755102 ],
       [10.        , 11.3877551 ,  7.54081633],
       [10.        , 11.40816327,  7.306

In [17]:
np.vstack((f, e))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])