<a href="https://colab.research.google.com/github/KuroCat-bite/Practice/blob/main/Shape_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shape and Operation

* reshape : mengubah dimensi (shape) dari sebuah numpy array
* vstack : stack numpy arrays secara vertikal
* hstack : stack numpy arrays secara horizontal
* vsplit : split numpy arrays secara vertikal
* hsplit : split numpy arrays secara horizontal

In [1]:
import numpy as np

In [85]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a = a.reshape((3, -1))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
b = np.array([(7, 8), (9, 10,)])

B

array([[ 7,  8,  9],
       [ 9, 10, 11]])

In [83]:
np.vstack ((a, b))


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [71]:
c = np.array([(11, 12, 13), (14, 15, 16)])

c

array([[11, 12, 13],
       [14, 15, 16]])

In [87]:
d = np.array((a, c))

d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [86]:
d = np.hstack((a, c))

d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])